[package]
name = "tiny_ram_db"
version = "0.1.3"
authors = ["werner <werner@yahoo.es>", "nubis <yo@nubis.im>"]
description = "A Tiny RAM Database for fast access"
license = "MIT/Apache-2.0"

[dependencies]
error-chain = "0.12.0"
